const STUDI = [
{
"id": "braccio_leva",
"pmid": "34404228",
"doi": "10.1098/rsif.2021.0326",
"titolo": "Knee extension moment arm variations relate to mechanical function in walking and running",
"rivista": "Journal of the Royal Society, Interface",
"anno": "2021",
"autore": "Wheatley MGA",
"oa": false,
"cit": 9,
"tema": "anatomia",
"liv": "B",
"sintesi": "Le variazioni individuali del braccio di leva dell’estensione del ginocchio si riflettono nella funzione meccanica. Spiega perché due persone con lo stesso muscolo esprimono forze diverse.",
"kw": "braccio di leva torque individuale"
},
{
"id": "memoria_muscolare",
"pmid": "29382913",
"doi": "10.1038/s41598-018-20287-3",
"titolo": "Human Skeletal Muscle Possesses an Epigenetic Memory of Hypertrophy",
"rivista": "Scientific reports",
"anno": "2018",
"autore": "Seaborne RA",
"oa": true,
"cit": 236,
"tema": "anatomia",
"liv": "B",
"sintesi": "Il muscolo umano conserva una memoria epigenetica dell’ipertrofia: dopo un periodo di stop, i geni coinvolti restano marcati e la ricrescita è più rapida.",
"kw": "memoria muscolare epigenetica ricrescita"
},
{
"id": "franchi_architettura",
"pmid": "24387247",
"doi": "10.1111/apha.12225",
"titolo": "Architectural, functional and molecular responses to concentric and eccentric loading in human skeletal muscle",
"rivista": "Acta physiologica (Oxford, England)",
"anno": "2014",
"autore": "Franchi MV",
"oa": false,
"cit": 265,
"tema": "anatomia",
"liv": "B",
"sintesi": "Carico concentrico ed eccentrico producono adattamenti architetturali diversi: l’eccentrico allunga i fascicoli, il concentrico aumenta l’angolo di pennazione.",
"kw": "architettura fascicoli pennazione"
},
{
"id": "plotkin_overload",
"pmid": "36199287",
"doi": "10.7717/peerj.14142",
"titolo": "Progressive overload without progressing load? The effects of load or repetition progression on muscular adaptations",
"rivista": "PeerJ",
"anno": "2022",
"autore": "Plotkin D",
"oa": true,
"cit": 40,
"tema": "carico",
"liv": "B",
"sintesi": "Progredire aggiungendo ripetizioni a parità di carico produce ipertrofia paragonabile a progredire aggiungendo carico. Il sovraccarico non deve per forza essere in chili.",
"kw": "sovraccarico progressivo ripetizioni carico"
},
{
"id": "lopez_load",
"pmid": "35029596",
"doi": "10.1249/mss.0000000000002838",
"titolo": "Resistance Training Load Effects on Muscle Hypertrophy and Strength Gain: Systematic Review and Network Meta-analysis-Corrigendum",
"rivista": "Medicine and science in sports and exercise",
"anno": "2022",
"autore": "",
"oa": false,
"cit": 3,
"tema": "carico",
"liv": "A",
"sintesi": "Meta-analisi a rete: per l’ipertrofia i carichi funzionano in un intervallo ampio, per la forza contano le percentuali alte.",
"kw": "carico rete meta-analisi"
},
{
"id": "continuum",
"pmid": "33671664",
"doi": "10.3390/sports9020032",
"titolo": "Loading Recommendations for Muscle Strength, Hypertrophy, and Local Endurance: A Re-Examination of the Repetition Continuum",
"rivista": "Sports (Basel, Switzerland)",
"anno": "2021",
"autore": "Schoenfeld BJ",
"oa": true,
"cit": 167,
"tema": "carico",
"liv": "A",
"sintesi": "Riesame del continuum delle ripetizioni: la divisione rigida fra zone di forza, ipertrofia e resistenza non regge. Per l’ipertrofia funziona un intervallo molto più ampio di quanto si insegnasse.",
"kw": "continuum ripetizioni zone carico"
},
{
"id": "korakakis_mindose",
"pmid": "31797219",
"doi": "10.1007/s40279-019-01236-0",
"titolo": "The Minimum Effective Training Dose Required to Increase 1RM Strength in Resistance-Trained Men: A Systematic Review and Meta-Analysis",
"rivista": "Sports medicine (Auckland, N.Z.)",
"anno": "2020",
"autore": "Androulakis-Korakakis P",
"oa": false,
"cit": 60,
"tema": "carico",
"liv": "B",
"sintesi": "Dose minima efficace per aumentare il massimale in uomini allenati: bastano volumi sorprendentemente contenuti per mantenere e far crescere la forza.",
"kw": "dose minima forza massimale"
},
{
"id": "schoenfeld_load",
"pmid": "28834797",
"doi": "10.1519/jsc.0000000000002200",
"titolo": "Strength and Hypertrophy Adaptations Between Low- vs. High-Load Resistance Training: A Systematic Review and Meta-analysis",
"rivista": "Journal of strength and conditioning research",
"anno": "2017",
"autore": "Schoenfeld BJ",
"oa": false,
"cit": 525,
"tema": "carico",
"liv": "A",
"sintesi": "Meta-analisi su carichi bassi contro alti: l’ipertrofia è simile in tutto lo spettro, la forza massimale invece migliora di più con i carichi alti.",
"kw": "carico ripetizioni pesante leggero"
},
{
"id": "schoenfeld_load15",
"pmid": "25853914",
"doi": "10.1519/jsc.0000000000000958",
"titolo": "Effects of Low- vs. High-Load Resistance Training on Muscle Strength and Hypertrophy in Well-Trained Men",
"rivista": "Journal of strength and conditioning research",
"anno": "2015",
"autore": "Schoenfeld BJ",
"oa": false,
"cit": 272,
"tema": "carico",
"liv": "B",
"sintesi": "Su uomini ben allenati, carichi bassi ad alte ripetizioni e carichi alti producono ipertrofia paragonabile, con vantaggio dei carichi alti sulla forza.",
"kw": "carico allenati ripetizioni"
},
{
"id": "grgic_rir_aff",
"pmid": "40644671",
"doi": "10.1519/jsc.0000000000005190",
"titolo": "Validity and Test-Retest Reliability of Repetitions-In-Reserve Across Different Low-Loads in the Barbell Bench Press With Blood Flow Restriction",
"rivista": "Journal of strength and conditioning research",
"anno": "2025",
"autore": "Grant WM",
"oa": false,
"cit": 0,
"tema": "cedimento",
"liv": "B",
"sintesi": "Validità e affidabilità della stima delle ripetizioni in riserva in esercizi diversi: funziona meglio vicino al cedimento e sulle macchine, peggio lontano e sui multiarticolari.",
"kw": "RIR affidabilità validità stima"
},
{
"id": "refalo_failure",
"pmid": "38970765",
"doi": "10.1007/s40279-024-02069-2",
"titolo": "Exploring the Dose-Response Relationship Between Estimated Resistance Training Proximity to Failure, Strength Gain, and Muscle Hypertrophy: A Series of Meta-Regressions",
"rivista": "Sports medicine (Auckland, N.Z.)",
"anno": "2024",
"autore": "Robinson ZP",
"oa": false,
"cit": 31,
"tema": "cedimento",
"liv": "A",
"sintesi": "Meta-regressione: l’ipertrofia aumenta man mano che le serie si avvicinano al cedimento, mentre i guadagni di forza sono sostanzialmente indifferenti alla vicinanza al cedimento.",
"kw": "cedimento RIR ipertrofia forza"
},
{
"id": "refalo_review",
"pmid": "36334240",
"doi": "10.1007/s40279-022-01784-y",
"titolo": "Influence of Resistance Training Proximity-to-Failure on Skeletal Muscle Hypertrophy: A Systematic Review with Meta-analysis",
"rivista": "Sports medicine (Auckland, N.Z.)",
"anno": "2023",
"autore": "Refalo MC",
"oa": true,
"cit": 32,
"tema": "cedimento",
"liv": "A",
"sintesi": "Rassegna sistematica: allenarsi vicino al cedimento è sufficiente, e non serve raggiungerlo per massimizzare l’ipertrofia.",
"kw": "cedimento RIR rassegna"
},
{
"id": "grgic_failure",
"pmid": "33497853",
"doi": "10.1016/j.jshs.2021.01.007",
"titolo": "Effects of resistance training performed to repetition failure or non-failure on muscular strength and hypertrophy: A systematic review and meta-analysis",
"rivista": "Journal of sport and health science",
"anno": "2022",
"autore": "Grgic J",
"oa": true,
"cit": 111,
"tema": "cedimento",
"liv": "A",
"sintesi": "Meta-analisi su cedimento contro non cedimento: nessuna differenza significativa di ipertrofia, con la fatica che è però molto maggiore andando a cedimento.",
"kw": "cedimento fatica"
},
{
"id": "doms_hypertrophy",
"pmid": "35658845",
"doi": "10.1080/02640414.2022.2080165",
"titolo": "Towards an improved understanding of proximity-to-failure in resistance training and its influence on skeletal muscle hypertrophy, neuromuscular fatigue, muscle damage, and perceived discomfort: A scoping review",
"rivista": "Journal of sports sciences",
"anno": "2022",
"autore": "Refalo MC",
"oa": false,
"cit": 31,
"tema": "cedimento",
"liv": "B",
"sintesi": "Rassegna concettuale sulla vicinanza al cedimento: chiarisce che indolenzimento e fatica non sono indicatori di stimolo.",
"kw": "indolenzimento DOMS fatica"
},
{
"id": "helms_rpe",
"pmid": "27243918",
"doi": "10.1519/jsc.0000000000001517",
"titolo": "RPE and Velocity Relationships for the Back Squat, Bench Press, and Deadlift in Powerlifters",
"rivista": "Journal of strength and conditioning research",
"anno": "2017",
"autore": "Helms ER",
"oa": false,
"cit": 81,
"tema": "cedimento",
"liv": "B",
"sintesi": "Relazione tra RPE, velocità del bilanciere e percentuale di massimale su squat, panca e stacco nei powerlifter.",
"kw": "RPE velocità massimale"
},
{
"id": "steele_effort",
"pmid": "29204323",
"doi": "10.7717/peerj.4105",
"titolo": "Ability to predict repetitions to momentary failure is not perfectly accurate, though improves with resistance training experience",
"rivista": "PeerJ",
"anno": "2017",
"autore": "Steele J",
"oa": true,
"cit": 33,
"tema": "cedimento",
"liv": "B",
"sintesi": "Le persone sbagliano sistematicamente a stimare quante ripetizioni mancano al cedimento, e tendono a sottostimare lo sforzo residuo. È il limite pratico di ogni prescrizione basata sul RIR.",
"kw": "RIR stima errore autovalutazione"
},
{
"id": "zourdos_rir",
"pmid": "26049792",
"doi": "10.1519/jsc.0000000000001049",
"titolo": "Novel Resistance Training-Specific Rating of Perceived Exertion Scale Measuring Repetitions in Reserve",
"rivista": "Journal of strength and conditioning research",
"anno": "2016",
"autore": "Zourdos MC",
"oa": false,
"cit": 268,
"tema": "cedimento",
"liv": "B",
"sintesi": "Costruzione e validazione della scala RPE basata sulle ripetizioni in riserva, quella che rende utilizzabile il concetto di RIR in palestra.",
"kw": "RIR RPE scala"
},
{
"id": "helms_rir_app",
"pmid": "27531969",
"doi": "10.1519/ssc.0000000000000218",
"titolo": "Application of the Repetitions in Reserve-Based Rating of Perceived Exertion Scale for Resistance Training",
"rivista": "Strength and conditioning journal",
"anno": "2016",
"autore": "Helms ER",
"oa": true,
"cit": 161,
"tema": "cedimento",
"liv": "B",
"sintesi": "Come si applica in pratica la scala RPE basata sulle ripetizioni in riserva nella programmazione. È il documento operativo dietro al concetto di RIR.",
"kw": "RIR RPE applicazione programmazione"
},
{
"id": "schoenfeld_freq",
"pmid": "30558493",
"doi": "10.1080/02640414.2018.1555906",
"titolo": "How many times per week should a muscle be trained to maximize muscle hypertrophy? A systematic review and meta-analysis of studies examining the effects of resistance training frequency",
"rivista": "Journal of sports sciences",
"anno": "2019",
"autore": "Schoenfeld BJ",
"oa": false,
"cit": 95,
"tema": "frequenza",
"liv": "A",
"sintesi": "Meta-analisi sulla frequenza: quando il volume settimanale è pareggiato, allenare un muscolo più volte a settimana non dà ipertrofia superiore.",
"kw": "frequenza volume pareggiato"
},
{
"id": "grgic_freq",
"pmid": "27102172",
"doi": "10.1007/s40279-016-0543-8",
"titolo": "Effects of Resistance Training Frequency on Measures of Muscle Hypertrophy: A Systematic Review and Meta-Analysis",
"rivista": "Sports medicine (Auckland, N.Z.)",
"anno": "2016",
"autore": "Schoenfeld BJ",
"oa": false,
"cit": 189,
"tema": "frequenza",
"liv": "A",
"sintesi": "Meta-analisi precedente sulla frequenza, che trovava un vantaggio per due sedute a settimana. Molti studi inclusi però non pareggiavano il volume: da leggere insieme all’aggiornamento del 2019.",
"kw": "frequenza due volte settimana"
},
{
"id": "tendine_carico",
"pmid": "42496412",
"doi": "10.3390/jfmk11030273",
"titolo": "Effects of Mechanical Loading on the Structure and Function of the Achilles Tendon: From Homeostatic Adaptation to Pathological Degeneration",
"rivista": "Journal of functional morphology and kinesiology",
"anno": "2026",
"autore": "Guan L",
"oa": true,
"cit": 0,
"tema": "infortuni",
"liv": "B",
"sintesi": "Effetti del carico meccanico su struttura e funzione del tendine d’Achille: il tendine si adatta al carico, ma con tempi più lunghi del muscolo.",
"kw": "tendine achille carico adattamento"
},
{
"id": "lombalgia_esercizio",
"pmid": "40106279",
"doi": null,
"titolo": "Exercise Therapy for Chronic Low Back Pain",
"rivista": "American family physician",
"anno": "2025",
"autore": "Skully R.",
"oa": false,
"cit": 0,
"tema": "infortuni",
"liv": "A",
"sintesi": "Terapia con esercizio per la lombalgia cronica: funziona, e nessuna modalità risulta chiaramente superiore alle altre. Il movimento in sé è la variabile attiva.",
"kw": "lombalgia cronica esercizio terapia"
},
{
"id": "spalla_impingement",
"pmid": "40092169",
"doi": "10.1136/bmjsem-2025-002523",
"titolo": "Effectiveness of a sport-specific exercise programme for overhead athletes with unilateral subacromial shoulder pain: a study protocol of a randomised controlled trial",
"rivista": "BMJ open sport & exercise medicine",
"anno": "2025",
"autore": "Guérineau F",
"oa": true,
"cit": 1,
"tema": "infortuni",
"liv": "B",
"sintesi": "Programma di esercizio specifico per atleti overhead con problemi di spalla: struttura dell’intervento e risultati.",
"kw": "spalla overhead esercizio riabilitazione"
},
{
"id": "mobilita_squat",
"pmid": "33713896",
"doi": "10.1016/j.gaitpost.2021.03.015",
"titolo": "Relationship between passive ankle dorsiflexion range, dynamic ankle dorsiflexion range and lower limb and trunk kinematics during the single-leg squat",
"rivista": "Gait & posture",
"anno": "2021",
"autore": "da Costa GV",
"oa": false,
"cit": 12,
"tema": "infortuni",
"liv": "B",
"sintesi": "Relazione fra escursione passiva della caviglia e comportamento dinamico nello squat: la mobilità di caviglia condiziona la profondità raggiungibile.",
"kw": "caviglia mobilità squat profondità"
},
{
"id": "nordic_prevenzione",
"pmid": "34520846",
"doi": "10.1016/j.jclinepi.2021.09.007",
"titolo": "Why methods matter in a meta-analysis: a reappraisal showed inconclusive injury preventive effect of Nordic hamstring exercise",
"rivista": "Journal of clinical epidemiology",
"anno": "2021",
"autore": "Impellizzeri FM",
"oa": false,
"cit": 38,
"tema": "infortuni",
"liv": "A",
"sintesi": "Riesame metodologico delle meta-analisi sul Nordic curl per la prevenzione degli infortuni agli ischiocrurali: quando si correggono i problemi di metodo, l’evidenza risulta inconcludente. Buon esempio di quanto conti come è fatto uno studio.",
"kw": "nordic prevenzione infortuni metodo"
},
{
"id": "stiramento_mobilita",
"pmid": "42551249",
"doi": "10.1016/j.rehab.2026.102153",
"titolo": "Optimal stretching dose for improving range of motion in non-athletes and athletes with hamstring shortening: a dose-response meta-analysis",
"rivista": "Annals of physical and rehabilitation medicine",
"anno": "2026",
"autore": "Mendez-Rebolledo G",
"oa": false,
"cit": 0,
"tema": "lunghezza",
"liv": "A",
"sintesi": "Dose ottimale di stiramento per aumentare l’escursione articolare in soggetti non atleti: quanto e quanto spesso serve davvero.",
"kw": "stretching dose escursione mobilità"
},
{
"id": "wolf_partials",
"pmid": "39959841",
"doi": "10.7717/peerj.18904",
"titolo": "Lengthened partial repetitions elicit similar muscular adaptations as full range of motion repetitions during resistance training in trained individuals",
"rivista": "PeerJ",
"anno": "2025",
"autore": "Wolf M",
"oa": true,
"cit": 3,
"tema": "lunghezza",
"liv": "B",
"sintesi": "Su soggetti allenati, 8 settimane: parziali allungati e range completo producono spessore muscolare e forza simili. Le parziali allungate non sono superiori, ma nemmeno inferiori.",
"kw": "parziali range completo allenati"
},
{
"id": "leg_ext_hip",
"pmid": "39699974",
"doi": "10.1080/02640414.2024.2444713",
"titolo": "The effects of hip flexion angle on quadriceps femoris muscle hypertrophy in the leg extension exercise",
"rivista": "Journal of sports sciences",
"anno": "2025",
"autore": "Larsen S",
"oa": false,
"cit": 11,
"tema": "lunghezza",
"liv": "B",
"sintesi": "Leg extension con anca a circa 40 gradi contro 90 gradi: la posizione più estesa allunga il retto femorale e ne produce più ipertrofia.",
"kw": "leg extension anca retto femorale schienale"
},
{
"id": "maeo_triceps",
"pmid": "35819335",
"doi": "10.1080/17461391.2022.2100279",
"titolo": "Triceps brachii hypertrophy is substantially greater after elbow extension training performed in the overhead versus neutral arm position",
"rivista": "European journal of sport science",
"anno": "2023",
"autore": "Maeo S",
"oa": false,
"cit": 22,
"tema": "lunghezza",
"liv": "A",
"sintesi": "Estensione del gomito sopra la testa contro braccio neutro, 12 settimane, disegno intra-soggetto. Tricipite +19,9% contro +13,5%: circa il 40% di crescita in più con la spalla flessa, perché il capo lungo parte allungato.",
"kw": "tricipiti overhead pushdown capo lungo"
},
{
"id": "kinoshita_calf",
"pmid": "38156065",
"doi": "10.3389/fphys.2023.1272106",
"titolo": "Triceps surae muscle hypertrophy is greater after standing versus seated calf-raise training",
"rivista": "Frontiers in physiology",
"anno": "2023",
"autore": "Kinoshita M",
"oa": true,
"cit": 12,
"tema": "lunghezza",
"liv": "A",
"sintesi": "Calf raise in piedi contro da seduto, 12 settimane. Gastrocnemio laterale +12,4% contro +1,7%, mediale +9,2% contro +0,6%. Il soleo invece cresce uguale nelle due condizioni (2,1% contro 2,9%).",
"kw": "polpacci gastrocnemio soleo calf raise"
},
{
"id": "kassiano_partials",
"pmid": "37015016",
"doi": "10.1519/jsc.0000000000004460",
"titolo": "Greater Gastrocnemius Muscle Hypertrophy After Partial Range of Motion Training Performed at Long Muscle Lengths",
"rivista": "Journal of strength and conditioning research",
"anno": "2023",
"autore": "Kassiano W",
"oa": false,
"cit": 29,
"tema": "lunghezza",
"liv": "B",
"sintesi": "Parziali nella porzione allungata producono più ipertrofia del gastrocnemio rispetto al range completo.",
"kw": "polpacci parziali gastrocnemio"
},
{
"id": "ottinger_stretch",
"pmid": "37556026",
"doi": "10.1007/s40279-023-01898-x",
"titolo": "Physiology of Stretch-Mediated Hypertrophy and Strength Increases: A Narrative Review",
"rivista": "Sports medicine (Auckland, N.Z.)",
"anno": "2023",
"autore": "Warneke K",
"oa": true,
"cit": 32,
"tema": "lunghezza",
"liv": "B",
"sintesi": "Rassegna narrativa sui meccanismi dell’ipertrofia mediata dallo stiramento: tensione passiva, danno meccanico e segnalazione anabolica. Utile per capire il perché, non per quantificare l’effetto.",
"kw": "stiramento meccanismi rassegna"
},
{
"id": "pedrosa_rom",
"pmid": "33977835",
"doi": "10.1080/17461391.2021.1927199",
"titolo": "Partial range of motion training elicits favorable improvements in muscular adaptations when carried out at long muscle lengths",
"rivista": "European journal of sport science",
"anno": "2022",
"autore": "Pedrosa GF",
"oa": false,
"cit": 30,
"tema": "lunghezza",
"liv": "B",
"sintesi": "Ripetizioni parziali svolte nella porzione allungata del movimento producono adattamenti pari o superiori al range completo sul quadricipite.",
"kw": "range di movimento parziali quadricipite"
},
{
"id": "warneke_stretch",
"pmid": "35694390",
"doi": "10.3389/fphys.2022.878955",
"titolo": "Influence of Long-Lasting Static Stretching on Maximal Strength, Muscle Thickness and Flexibility",
"rivista": "Frontiers in physiology",
"anno": "2022",
"autore": "Warneke K",
"oa": true,
"cit": 41,
"tema": "lunghezza",
"liv": "B",
"sintesi": "Stiramento statico prolungato quotidiano produce aumenti misurabili di spessore muscolare e forza. Interessante come prova del principio della lunghezza, non come sostituto dell’allenamento.",
"kw": "stretching statico spessore"
},
{
"id": "maeo_hamstring",
"pmid": "33009197",
"doi": "10.1249/mss.0000000000002523",
"titolo": "Greater Hamstrings Muscle Hypertrophy but Similar Damage Protection after Training at Long versus Short Muscle Lengths",
"rivista": "Medicine and science in sports and exercise",
"anno": "2021",
"autore": "Maeo S",
"oa": true,
"cit": 48,
"tema": "lunghezza",
"liv": "A",
"sintesi": "Stessa persona, una gamba con leg curl seduto e una con leg curl prono, 12 settimane. Il volume degli ischiocrurali cresce del 14% da seduto contro il 9% da prono. La differenza c’è su semimembranoso, semitendinoso e capo lungo del bicipite femorale — non sul capo breve, l’unico che non attraversa l’anca.",
"kw": "leg curl femorali ischiocrurali lunghezza seduto prono"
},
{
"id": "sato_rom",
"pmid": "34616309",
"doi": "10.3389/fphys.2021.734509",
"titolo": "Elbow Joint Angles in Elbow Flexor Unilateral Resistance Exercise Training Determine Its Effects on Muscle Strength and Thickness of Trained and Non-trained Arms",
"rivista": "Frontiers in physiology",
"anno": "2021",
"autore": "Sato S",
"oa": true,
"cit": 21,
"tema": "lunghezza",
"liv": "B",
"sintesi": "Curl allenato ad angoli di gomito diversi: la posizione che tiene il flessore più lungo produce più spessore muscolare.",
"kw": "bicipiti angolo gomito lunghezza"
},
{
"id": "kubo_moment",
"pmid": "31230110",
"doi": "10.1007/s00421-019-04181-y",
"titolo": "Effects of squat training with different depths on lower limb muscle volumes",
"rivista": "European journal of applied physiology",
"anno": "2019",
"autore": "Kubo K",
"oa": false,
"cit": 79,
"tema": "lunghezza",
"liv": "B",
"sintesi": "Squat allenato a profondità diverse: i volumi dei muscoli degli arti inferiori rispondono in modo diverso, a favore della maggiore profondità.",
"kw": "squat profondità volumi muscolari"
},
{
"id": "squat_depth",
"pmid": "23604798",
"doi": "10.1007/s00421-013-2642-7",
"titolo": "Effect of range of motion in heavy load squatting on muscle and tendon adaptations",
"rivista": "European journal of applied physiology",
"anno": "2013",
"autore": "Bloomquist K",
"oa": false,
"cit": 114,
"tema": "lunghezza",
"liv": "B",
"sintesi": "Squat profondo contro squat parziale con carico pesante, 12 settimane: il profondo produce più ipertrofia sul quadricipite e adattamenti tendinei maggiori.",
"kw": "squat profondità range quadricipite"
},
{
"id": "roberts_mechanisms",
"pmid": "37382939",
"doi": "10.1152/physrev.00039.2022",
"titolo": "Mechanisms of mechanical overload-induced skeletal muscle hypertrophy: current understanding and future directions",
"rivista": "Physiological reviews",
"anno": "2023",
"autore": "Roberts MD",
"oa": false,
"cit": 168,
"tema": "meccanismi",
"liv": "A",
"sintesi": "Stato dell’arte sui meccanismi dell’ipertrofia da sovraccarico meccanico: cosa sappiamo e cosa resta aperto.",
"kw": "meccanismi sovraccarico stato arte"
},
{
"id": "roberts_sarcoplasma",
"pmid": "32760293",
"doi": "10.3389/fphys.2020.00816",
"titolo": "Sarcoplasmic Hypertrophy in Skeletal Muscle: A Scientific \"Unicorn\" or Resistance Training Adaptation?",
"rivista": "Frontiers in physiology",
"anno": "2020",
"autore": "Roberts MD",
"oa": true,
"cit": 47,
"tema": "meccanismi",
"liv": "A",
"sintesi": "L’ipertrofia sarcoplasmatica esiste davvero o è un’invenzione da palestra? Esame critico delle prove: c’è qualcosa, ma non quello che si racconta.",
"kw": "sarcoplasmatica miofibrillare unicorno"
},
{
"id": "wackerhage_mech",
"pmid": "30335577",
"doi": "10.1152/japplphysiol.00685.2018",
"titolo": "Stimuli and sensors that initiate skeletal muscle hypertrophy following resistance exercise",
"rivista": "Journal of applied physiology (Bethesda, Md. : 1985)",
"anno": "2019",
"autore": "Wackerhage H",
"oa": false,
"cit": 234,
"tema": "meccanismi",
"liv": "A",
"sintesi": "Quali stimoli e quali sensori cellulari avviano l’ipertrofia dopo l’esercizio contro resistenza.",
"kw": "meccanismi sensori segnalazione"
},
{
"id": "damas_timeline",
"pmid": "27219125",
"doi": "10.1113/jp272472",
"titolo": "Resistance training-induced changes in integrated myofibrillar protein synthesis are related to hypertrophy only after attenuation of muscle damage",
"rivista": "The Journal of physiology",
"anno": "2016",
"autore": "Damas F",
"oa": false,
"cit": 244,
"tema": "meccanismi",
"liv": "B",
"sintesi": "Nelle prime settimane l’aumento di sintesi proteica è in gran parte riparazione del danno, non crescita: la sintesi correla con l’ipertrofia solo dopo che il danno si attenua.",
"kw": "sintesi proteica danno principianti"
},
{
"id": "damas_edema",
"pmid": "26280652",
"doi": "10.1007/s00421-015-3243-4",
"titolo": "Early resistance training-induced increases in muscle cross-sectional area are concomitant with edema-induced muscle swelling",
"rivista": "European journal of applied physiology",
"anno": "2016",
"autore": "Damas F",
"oa": false,
"cit": 137,
"tema": "meccanismi",
"liv": "B",
"sintesi": "Nelle prime settimane l’aumento di sezione muscolare misurato è in buona parte gonfiore da edema, non tessuto nuovo. Motivo per cui gli studi brevi sovrastimano l’ipertrofia dei principianti.",
"kw": "edema gonfiore sezione principianti"
},
{
"id": "fyfe_interferenza",
"pmid": "24728927",
"doi": "10.1007/s40279-014-0162-1",
"titolo": "Interference between concurrent resistance and endurance exercise: molecular bases and the role of individual training variables",
"rivista": "Sports medicine (Auckland, N.Z.)",
"anno": "2014",
"autore": "Fyfe JJ",
"oa": false,
"cit": 200,
"tema": "meccanismi",
"liv": "B",
"sintesi": "I meccanismi molecolari dell’interferenza fra resistenza ed endurance: cosa accade davvero nelle vie di segnalazione, al di là dell’aneddoto.",
"kw": "interferenza molecolare segnalazione"
},
{
"id": "schoenfeld_mechanisms",
"pmid": "20847704",
"doi": "10.1519/jsc.0b013e3181e840f3",
"titolo": "The mechanisms of muscle hypertrophy and their application to resistance training",
"rivista": "Journal of strength and conditioning research",
"anno": "2010",
"autore": "Schoenfeld BJ.",
"oa": false,
"cit": 652,
"tema": "meccanismi",
"liv": "A",
"sintesi": "La rassegna che ha reso popolare la tripartizione tensione meccanica, stress metabolico e danno muscolare. Storicamente centrale, oggi in parte superata sul ruolo del danno.",
"kw": "meccanismi tensione stress metabolico danno"
},
{
"id": "vieira_intraserie",
"pmid": "42632634",
"doi": "10.1123/ijspp.2025-0209",
"titolo": "Systematic Differences in Mean Rating of Perceived Exertion and Session Rating of Perceived Exertion During Training and Competition",
"rivista": "International journal of sports physiology and performance",
"anno": "2026",
"autore": "Foster C",
"oa": false,
"cit": 0,
"tema": "metodo",
"liv": "B",
"sintesi": "Differenze sistematiche fra sforzo percepito medio e sforzo percepito della seduta: due misure che non si possono usare come se fossero la stessa cosa.",
"kw": "RPE seduta misura sforzo"
},
{
"id": "dexa_ultrasuoni",
"pmid": "41502398",
"doi": "10.1111/cpf.70045",
"titolo": "Intra- and inter-observer reliability of ultrasound muscle thickness of gluteal and biceps femoris long head in individuals with and without SCI",
"rivista": "Clinical physiology and functional imaging",
"anno": "2026",
"autore": "Wijker BJ",
"oa": true,
"cit": 1,
"tema": "metodo",
"liv": "B",
"sintesi": "Affidabilità intra e inter-operatore della misura ecografica dello spessore muscolare. Serve a capire quanto rumore c’è nei numeri che leggi negli studi.",
"kw": "ecografia affidabilità misura spessore"
},
{
"id": "coratella_emg",
"pmid": "35907047",
"doi": "10.1186/s40798-022-00492-1",
"titolo": "Appropriate Reporting of Exercise Variables in Resistance Training Protocols: Much more than Load and Number of Repetitions",
"rivista": "Sports medicine - open",
"anno": "2022",
"autore": "Coratella G.",
"oa": true,
"cit": 50,
"tema": "metodo",
"liv": "C",
"sintesi": "Come vanno riportate le variabili di un protocollo di allenamento perché lo studio sia interpretabile. Utile per valutare la qualità di quello che leggi.",
"kw": "metodologia variabili protocollo"
},
{
"id": "haun_hypertrophy",
"pmid": "30930796",
"doi": "10.3389/fphys.2019.00247",
"titolo": "A Critical Evaluation of the Biological Construct Skeletal Muscle Hypertrophy: Size Matters but So Does the Measurement",
"rivista": "Frontiers in physiology",
"anno": "2019",
"autore": "Haun CT",
"oa": true,
"cit": 126,
"tema": "metodo",
"liv": "A",
"sintesi": "Valutazione critica del concetto stesso di ipertrofia: cosa misurano davvero ecografia, risonanza e biopsia, e perché studi diversi possono dire cose diverse.",
"kw": "misura ipertrofia metodi critica"
},
{
"id": "vigotsky_emg",
"pmid": "29354060",
"doi": "10.3389/fphys.2017.00985",
"titolo": "Interpreting Signal Amplitudes in Surface Electromyography Studies in Sport and Rehabilitation Sciences",
"rivista": "Frontiers in physiology",
"anno": "2017",
"autore": "Vigotsky AD",
"oa": true,
"cit": 294,
"tema": "metodo",
"liv": "A",
"sintesi": "Perché l’ampiezza del segnale elettromiografico non è una misura di quanto un esercizio farà crescere un muscolo. Da leggere prima di credere a qualunque classifica basata su EMG.",
"kw": "EMG attivazione limiti interpretazione"
},
{
"id": "guest_caffeina",
"pmid": "33388079",
"doi": "10.1186/s12970-020-00383-4",
"titolo": "International society of sports nutrition position stand: caffeine and exercise performance",
"rivista": "Journal of the International Society of Sports Nutrition",
"anno": "2021",
"autore": "Guest NS",
"oa": true,
"cit": 415,
"tema": "nutrizione",
"liv": "A",
"sintesi": "Documento di posizione sulla caffeina: migliora la prestazione in molti contesti, con dosi e tempistiche indicate. Sulla forza massimale l’effetto è più piccolo che sulla resistenza.",
"kw": "caffeina prestazione dose"
},
{
"id": "morton_protein",
"pmid": "28698222",
"doi": "10.1136/bjsports-2017-097608",
"titolo": "A systematic review, meta-analysis and meta-regression of the effect of protein supplementation on resistance training-induced gains in muscle mass and strength in healthy adults",
"rivista": "British journal of sports medicine",
"anno": "2018",
"autore": "Morton RW",
"oa": true,
"cit": 763,
"tema": "nutrizione",
"liv": "A",
"sintesi": "Meta-analisi e meta-regressione sulle proteine: l’integrazione aumenta massa e forza da allenamento, con un plateau intorno a 1,6 g per kg al giorno.",
"kw": "proteine integrazione grammi massa"
},
{
"id": "kreider_creatina",
"pmid": "28615996",
"doi": "10.1186/s12970-017-0173-z",
"titolo": "International Society of Sports Nutrition position stand: safety and efficacy of creatine supplementation in exercise, sport, and medicine",
"rivista": "Journal of the International Society of Sports Nutrition",
"anno": "2017",
"autore": "Kreider RB",
"oa": true,
"cit": 485,
"tema": "nutrizione",
"liv": "A",
"sintesi": "Documento di posizione della International Society of Sports Nutrition sulla creatina monoidrato: efficace sulla forza e sulla massa magra, con un profilo di sicurezza fra i meglio documentati di qualunque integratore.",
"kw": "creatina integratore sicurezza"
},
{
"id": "jager_proteine",
"pmid": "28642676",
"doi": "10.1186/s12970-017-0177-8",
"titolo": "International Society of Sports Nutrition Position Stand: protein and exercise",
"rivista": "Journal of the International Society of Sports Nutrition",
"anno": "2017",
"autore": "Jäger R",
"oa": true,
"cit": 523,
"tema": "nutrizione",
"liv": "A",
"sintesi": "Documento di posizione sulle proteine: quantità giornaliera, distribuzione nei pasti e qualità della fonte. È il riferimento pratico da cui partire.",
"kw": "proteine distribuzione fonte"
},
{
"id": "murphy_deficit",
"pmid": "25738784",
"doi": "10.1152/ajpendo.00550.2014",
"titolo": "Hypoenergetic diet-induced reductions in myofibrillar protein synthesis are restored with resistance training and balanced daily protein ingestion in older men",
"rivista": "American journal of physiology. Endocrinology and metabolism",
"anno": "2015",
"autore": "Murphy CH",
"oa": false,
"cit": 80,
"tema": "nutrizione",
"liv": "B",
"sintesi": "In deficit calorico la sintesi proteica miofibrillare cala, ma allenamento contro resistenza e apporto proteico adeguato distribuito nella giornata la riportano su.",
"kw": "deficit calorico dieta sintesi proteica"
},
{
"id": "trexler_metabolic",
"pmid": "24571926",
"doi": "10.1186/1550-2783-11-7",
"titolo": "Metabolic adaptation to weight loss: implications for the athlete",
"rivista": "Journal of the International Society of Sports Nutrition",
"anno": "2014",
"autore": "Trexler ET",
"oa": true,
"cit": 110,
"tema": "nutrizione",
"liv": "A",
"sintesi": "Cosa succede al metabolismo durante e dopo una perdita di peso in atleti, e come limitarne gli adattamenti sfavorevoli.",
"kw": "metabolismo dieta perdita peso"
},
{
"id": "helms_nutrition",
"pmid": "24864135",
"doi": "10.1186/1550-2783-11-20",
"titolo": "Evidence-based recommendations for natural bodybuilding contest preparation: nutrition and supplementation",
"rivista": "Journal of the International Society of Sports Nutrition",
"anno": "2014",
"autore": "Helms ER",
"oa": true,
"cit": 114,
"tema": "nutrizione",
"liv": "A",
"sintesi": "Raccomandazioni basate sull’evidenza per la preparazione a una gara natural: calorie, macronutrienti, tempistiche, integratori.",
"kw": "nutrizione gara natural preparazione"
},
{
"id": "schoenfeld_timing",
"pmid": "24299050",
"doi": "10.1186/1550-2783-10-53",
"titolo": "The effect of protein timing on muscle strength and hypertrophy: a meta-analysis",
"rivista": "Journal of the International Society of Sports Nutrition",
"anno": "2013",
"autore": "Schoenfeld BJ",
"oa": true,
"cit": 119,
"tema": "nutrizione",
"liv": "A",
"sintesi": "Meta-analisi sulla tempistica delle proteine: l’effetto apparente del timing sparisce quando si correggono le differenze di apporto totale. Conta quanto mangi, non quando.",
"kw": "timing proteine finestra"
},
{
"id": "aragon_timing",
"pmid": "23360586",
"doi": "10.1186/1550-2783-10-5",
"titolo": "Nutrient timing revisited: is there a post-exercise anabolic window?",
"rivista": "Journal of the International Society of Sports Nutrition",
"anno": "2013",
"autore": "Aragon AA",
"oa": true,
"cit": 75,
"tema": "nutrizione",
"liv": "A",
"sintesi": "La rassegna che ha smontato la finestra anabolica dei trenta minuti, mostrando che il quadro reale è molto più permissivo.",
"kw": "finestra anabolica post allenamento"
},
{
"id": "deload",
"pmid": "38274324",
"doi": "10.7717/peerj.16777",
"titolo": "Gaining more from doing less? The effects of a one-week deload period during supervised resistance training on muscular adaptations",
"rivista": "PeerJ",
"anno": "2024",
"autore": "Coleman M",
"oa": true,
"cit": 5,
"tema": "organizzazione",
"liv": "B",
"sintesi": "Una settimana di scarico a metà di un programma di 9 settimane non migliora né peggiora l’ipertrofia, e riduce leggermente la forza nel breve.",
"kw": "scarico deload settimana"
},
{
"id": "petre_concurrent",
"pmid": "38187085",
"doi": "10.1016/j.jesf.2023.12.005",
"titolo": "Comparative efficacy of concurrent training types on lower limb strength and muscular hypertrophy: A systematic review and network meta-analysis",
"rivista": "Journal of exercise science and fitness",
"anno": "2024",
"autore": "Chen Y",
"oa": true,
"cit": 8,
"tema": "organizzazione",
"liv": "A",
"sintesi": "Confronto fra tipi di allenamento concorrente su forza e ipertrofia degli arti inferiori: le modalità non sono equivalenti.",
"kw": "concorrente cardio forza"
},
{
"id": "iversen_nopain",
"pmid": "34784019",
"doi": "10.1007/s40279-021-01592-w",
"titolo": "Response to Comment on: \"No Time to Lift? Designing Time-Efficient Training Programs for Strength and Hypertrophy: A Narrative Review\"",
"rivista": "Sports medicine (Auckland, N.Z.)",
"anno": "2022",
"autore": "Iversen VM",
"oa": false,
"cit": 2,
"tema": "organizzazione",
"liv": "B",
"sintesi": "Come costruire programmi efficienti quando il tempo è poco: cosa tagliare per primo senza perdere risultati.",
"kw": "tempo efficienza programma minimo"
},
{
"id": "craven_sleep",
"pmid": "35708888",
"doi": "10.1007/s40279-022-01706-y",
"titolo": "Effects of Acute Sleep Loss on Physical Performance: A Systematic and Meta-Analytical Review",
"rivista": "Sports medicine (Auckland, N.Z.)",
"anno": "2022",
"autore": "Craven J",
"oa": true,
"cit": 90,
"tema": "organizzazione",
"liv": "A",
"sintesi": "Meta-analisi sulla privazione acuta di sonno: la prestazione fisica peggiora, e l’effetto è più marcato nel pomeriggio e sulle attività prolungate.",
"kw": "sonno privazione prestazione"
},
{
"id": "nunes_order",
"pmid": "32077380",
"doi": "10.1080/17461391.2020.1733672",
"titolo": "What influence does resistance exercise order have on muscular strength gains and muscle hypertrophy? A systematic review and meta-analysis",
"rivista": "European journal of sport science",
"anno": "2021",
"autore": "Nunes JP",
"oa": false,
"cit": 40,
"tema": "organizzazione",
"liv": "A",
"sintesi": "Meta-analisi sull’ordine degli esercizi: chi va per primo guadagna più forza, ma l’ordine non ha effetto significativo sull’ipertrofia.",
"kw": "ordine esercizi sequenza"
},
{
"id": "greig_autoreg",
"pmid": "32813181",
"doi": "10.1007/s40279-020-01330-8",
"titolo": "Autoregulation in Resistance Training: Addressing the Inconsistencies",
"rivista": "Sports medicine (Auckland, N.Z.)",
"anno": "2020",
"autore": "Greig L",
"oa": true,
"cit": 48,
"tema": "organizzazione",
"liv": "B",
"sintesi": "Rassegna critica sull’autoregolazione: il termine viene usato per pratiche molto diverse fra loro, e questo rende difficile confrontare gli studi. Utile per capire cosa si sta davvero misurando.",
"kw": "autoregolazione definizioni"
},
{
"id": "knowles_sleep",
"pmid": "29422383",
"doi": "10.1016/j.jsams.2018.01.012",
"titolo": "Inadequate sleep and muscle strength: Implications for resistance training",
"rivista": "Journal of science and medicine in sport",
"anno": "2018",
"autore": "Knowles OE",
"oa": false,
"cit": 74,
"tema": "organizzazione",
"liv": "B",
"sintesi": "Rassegna sul sonno insufficiente e la forza muscolare, con le implicazioni pratiche per chi si allena contro resistenza.",
"kw": "sonno forza recupero"
},
{
"id": "period_meta",
"pmid": "28497285",
"doi": "10.1007/s40279-017-0734-y",
"titolo": "Comparison of Periodized and Non-Periodized Resistance Training on Maximal Strength: A Meta-Analysis",
"rivista": "Sports medicine (Auckland, N.Z.)",
"anno": "2017",
"autore": "Williams TD",
"oa": false,
"cit": 94,
"tema": "organizzazione",
"liv": "A",
"sintesi": "Meta-analisi su periodizzazione contro programmazione non periodizzata: la periodizzazione dà guadagni di forza maggiori, con differenze fra i modelli piccole.",
"kw": "periodizzazione forza modelli"
},
{
"id": "hackett_practices",
"pmid": "22990567",
"doi": "10.1519/jsc.0b013e318271272a",
"titolo": "Training practices and ergogenic aids used by male bodybuilders",
"rivista": "Journal of strength and conditioning research",
"anno": "2013",
"autore": "Hackett DA",
"oa": false,
"cit": 99,
"tema": "organizzazione",
"liv": "C",
"sintesi": "Indagine su cosa fanno davvero i bodybuilder in preparazione: volumi, frequenze, tecniche. Descrive la pratica, non dimostra che funzioni.",
"kw": "bodybuilder pratica indagine"
},
{
"id": "bosquet_detraining",
"pmid": "23347054",
"doi": "10.1111/sms.12047",
"titolo": "Effect of training cessation on muscular performance: a meta-analysis",
"rivista": "Scandinavian journal of medicine & science in sports",
"anno": "2013",
"autore": "Bosquet L",
"oa": false,
"cit": 85,
"tema": "organizzazione",
"liv": "A",
"sintesi": "Meta-analisi sull’interruzione dell’allenamento: la forza cala in modo misurabile e il tasso di perdita dipende dalla durata dello stop e dal livello di partenza.",
"kw": "interruzione detraining perdita"
},
{
"id": "ogasawara_ritorno",
"pmid": "23053130",
"doi": "10.1007/s00421-012-2511-9",
"titolo": "Comparison of muscle hypertrophy following 6-month of continuous and periodic strength training",
"rivista": "European journal of applied physiology",
"anno": "2013",
"autore": "Ogasawara R",
"oa": false,
"cit": 66,
"tema": "organizzazione",
"liv": "B",
"sintesi": "Sei mesi di allenamento continuo contro periodi alternati di stop e ripresa producono ipertrofia finale simile. Interessante per chi si ferma per forza.",
"kw": "stop ripresa continuo periodico"
},
{
"id": "schoenfeld_concurrent",
"pmid": "22002517",
"doi": "10.1519/jsc.0b013e31823a3e2d",
"titolo": "Concurrent training:  a meta-analysis examining interference of aerobic and resistance exercises",
"rivista": "Journal of strength and conditioning research",
"anno": "2012",
"autore": "Wilson JM",
"oa": false,
"cit": 332,
"tema": "organizzazione",
"liv": "A",
"sintesi": "Meta-analisi sull’interferenza fra allenamento aerobico e contro resistenza: l’effetto negativo esiste ma dipende da modalità, durata e frequenza dell’aerobico. Correre interferisce più che pedalare.",
"kw": "cardio concorrente interferenza aerobico"
},
{
"id": "acsm_posizione",
"pmid": "19204579",
"doi": "10.1249/mss.0b013e3181915670",
"titolo": "American College of Sports Medicine position stand. Progression models in resistance training for healthy adults",
"rivista": "Medicine and science in sports and exercise",
"anno": "2009",
"autore": "American College of Sports Medicine.",
"oa": false,
"cit": 2501,
"tema": "organizzazione",
"liv": "A",
"sintesi": "Documento di posizione dell’American College of Sports Medicine sui modelli di progressione. Storicamente centrale, in alcuni punti superato dalla ricerca successiva.",
"kw": "progressione linee guida posizione"
},
{
"id": "bird_variabili",
"pmid": "16180944",
"doi": "10.2165/00007256-200535100-00002",
"titolo": "Designing resistance training programmes to enhance muscular fitness: a review of the acute programme variables",
"rivista": "Sports medicine (Auckland, N.Z.)",
"anno": "2005",
"autore": "Bird SP",
"oa": false,
"cit": 296,
"tema": "organizzazione",
"liv": "C",
"sintesi": "Rassegna classica sulle variabili acute del programma: carico, volume, densità, ordine, recupero. Utile come mappa dei termini, datata sui numeri.",
"kw": "variabili programma progettazione"
},
{
"id": "roberts_responders",
"pmid": "39143904",
"doi": "10.1152/japplphysiol.00354.2024",
"titolo": "Androgen receptor markers do not differ between nonresponders and responders to resistance training-induced muscle hypertrophy",
"rivista": "Journal of applied physiology (Bethesda, Md. : 1985)",
"anno": "2024",
"autore": "Bergamasco JGA",
"oa": false,
"cit": 1,
"tema": "popolazioni",
"liv": "B",
"sintesi": "I marcatori del recettore degli androgeni non distinguono chi risponde da chi non risponde all’allenamento. Un candidato in meno fra le spiegazioni della variabilità.",
"kw": "responder androgeni variabilità"
},
{
"id": "nuzzo_sesso",
"pmid": "36696264",
"doi": "10.1519/jsc.0000000000004329",
"titolo": "Narrative Review of Sex Differences in Muscle Strength, Endurance, Activation, Size, Fiber Type, and Strength Training Participation Rates, Preferences, Motivations, Injuries, and Neuromuscular Adaptations",
"rivista": "Journal of strength and conditioning research",
"anno": "2023",
"autore": "Nuzzo JL.",
"oa": false,
"cit": 196,
"tema": "popolazioni",
"liv": "A",
"sintesi": "Rassegna ampia sulle differenze fra i sessi in forza, resistenza, attivazione, dimensione e tipo di fibra. Le differenze assolute sono grandi, quelle relative alla sezione muscolare molto meno.",
"kw": "sesso donne uomini differenze"
},
{
"id": "borde_anziani",
"pmid": "26420238",
"doi": "10.1007/s40279-015-0385-9",
"titolo": "Dose-Response Relationships of Resistance Training in Healthy Old Adults: A Systematic Review and Meta-Analysis",
"rivista": "Sports medicine (Auckland, N.Z.)",
"anno": "2015",
"autore": "Borde R",
"oa": true,
"cit": 455,
"tema": "popolazioni",
"liv": "A",
"sintesi": "Relazioni dose-risposta negli anziani sani: durata, frequenza, volume e intensità che producono i guadagni migliori. Le raccomandazioni non sono le stesse dei giovani.",
"kw": "anziani dose risposta età"
},
{
"id": "risposta_variabile",
"pmid": "15947721",
"doi": null,
"titolo": "Variability in muscle size and strength gain after unilateral resistance training",
"rivista": "Medicine and science in sports and exercise",
"anno": "2005",
"autore": "Hubal MJ",
"oa": false,
"cit": 277,
"tema": "popolazioni",
"liv": "A",
"sintesi": "Lo studio classico sulla variabilità: allenando un braccio in 585 persone, i guadagni vanno da nulli a oltre il 50%. Lo stesso programma non dà lo stesso risultato a due persone.",
"kw": "variabilità risposta individuale responder"
},
{
"id": "singer_rest",
"pmid": "39205815",
"doi": "10.3389/fspor.2024.1429789",
"titolo": "Give it a rest: a systematic review with Bayesian meta-analysis on the effect of inter-set rest interval duration on muscle hypertrophy",
"rivista": "Frontiers in sports and active living",
"anno": "2024",
"autore": "Singer A",
"oa": true,
"cit": 8,
"tema": "recupero",
"liv": "A",
"sintesi": "Meta-analisi bayesiana sui recuperi tra le serie: la crescita migliore si osserva intorno a 1-2 minuti, e le differenze fra le fasce di recupero sono piccole. Oltre i 2 minuti non emerge un vantaggio.",
"kw": "recupero pause tra serie"
},
{
"id": "grgic_rest",
"pmid": "28933024",
"doi": "10.1007/s40279-017-0788-x",
"titolo": "Effects of Rest Interval Duration in Resistance Training on Measures of Muscular Strength: A Systematic Review",
"rivista": "Sports medicine (Auckland, N.Z.)",
"anno": "2018",
"autore": "Grgic J",
"oa": false,
"cit": 84,
"tema": "recupero",
"liv": "A",
"sintesi": "Meta-analisi sui recuperi e la forza: pause più lunghe favoriscono i guadagni di forza, con effetto più marcato sui multiarticolari.",
"kw": "recupero forza multiarticolari"
},
{
"id": "schoenfeld_rest",
"pmid": "26605807",
"doi": "10.1519/jsc.0000000000001272",
"titolo": "Longer Interset Rest Periods Enhance Muscle Strength and Hypertrophy in Resistance-Trained Men",
"rivista": "Journal of strength and conditioning research",
"anno": "2016",
"autore": "Schoenfeld BJ",
"oa": false,
"cit": 94,
"tema": "recupero",
"liv": "B",
"sintesi": "Su allenati, 3 minuti di recupero producono più forza e ipertrofia di 1 minuto. È il lavoro che ha spostato la pratica verso recuperi lunghi.",
"kw": "recupero tre minuti un minuto"
},
{
"id": "squat_stance",
"pmid": "42579678",
"doi": "10.1371/journal.pone.0354893",
"titolo": "The effects of bar positioning, stance width, repetition, and load on muscle activity during the barbell back squat",
"rivista": "PloS one",
"anno": "2026",
"autore": "Lee CXY",
"oa": false,
"cit": 0,
"tema": "selezione",
"liv": "B",
"sintesi": "Effetti di posizione del bilanciere, larghezza della base, ripetizione e carico sull’attivazione muscolare nello squat.",
"kw": "squat stance larghezza bilanciere"
},
{
"id": "lateral_raise",
"pmid": "40692697",
"doi": "10.3389/fphys.2025.1611468",
"titolo": "Dumbbell versus cable lateral raises for lateral deltoid hypertrophy: an experimental study",
"rivista": "Frontiers in physiology",
"anno": "2025",
"autore": "Larsen S",
"oa": true,
"cit": 2,
"tema": "selezione",
"liv": "B",
"sintesi": "Alzate laterali con cavi contro manubri, 8 settimane su allenati, un braccio per condizione: nessuna differenza di spessore del deltoide laterale. Il profilo di resistenza non cambia il risultato.",
"kw": "alzate laterali cavi manubri deltoide"
},
{
"id": "adductor_squat",
"pmid": "40139264",
"doi": "10.1152/japplphysiol.00600.2024",
"titolo": "Redefining muscular action: human \"adductor\" magnus is designed to act primarily for hip \"extension\" rather than adduction in living young individuals",
"rivista": "Journal of applied physiology (Bethesda, Md. : 1985)",
"anno": "2025",
"autore": "Takahashi K",
"oa": false,
"cit": 4,
"tema": "selezione",
"liv": "B",
"sintesi": "L’adduttore magno umano è costruito soprattutto per estendere l’anca, non per addurre: nello squat contribuisce in modo rilevante alla spinta, e questo lo rende un muscolo da allenare per la coscia.",
"kw": "adduttore magno anca squat coscia"
},
{
"id": "biceps_regional",
"pmid": "39449136",
"doi": "10.1177/19417381241287522",
"titolo": "Similar Regional Hypertrophy of the Elbow Flexor Muscles in Response to Low-Load Training With Vascular Occlusion at Short Versus Long Muscle Lengths",
"rivista": "Sports health",
"anno": "2025",
"autore": "da Silva Vendruscolo L",
"oa": false,
"cit": 1,
"tema": "selezione",
"liv": "B",
"sintesi": "Confronto di ipertrofia regionale dei flessori del gomito fra condizioni: la crescita risulta simile lungo il muscolo.",
"kw": "bicipiti regionale flessori gomito"
},
{
"id": "stacco_stile",
"pmid": "40497251",
"doi": "10.3389/fbioe.2025.1597209",
"titolo": "Biomechanical analysis of conventional and sumo deadlift",
"rivista": "Frontiers in bioengineering and biotechnology",
"anno": "2025",
"autore": "Hanen NC",
"oa": true,
"cit": 1,
"tema": "selezione",
"liv": "B",
"sintesi": "Analisi biomeccanica di stacco convenzionale e sumo: distribuzione del carico e richieste articolari diverse a parità di peso sollevato.",
"kw": "stacco sumo convenzionale biomeccanica"
},
{
"id": "hip_thrust_squat",
"pmid": "40988435",
"doi": "10.1080/14763141.2025.2553700",
"titolo": "Comparing the impact of hip thrust versus squat training on lower limb performance in sub-elite athletes: a systematic review and meta-analysis",
"rivista": "Sports biomechanics",
"anno": "2025",
"autore": "Asghari SH",
"oa": false,
"cit": 1,
"tema": "selezione",
"liv": "B",
"sintesi": "Hip thrust contro squat sugli arti inferiori: caricano il gluteo in posizioni opposte e i risultati non sono interscambiabili.",
"kw": "hip thrust squat gluteo"
},
{
"id": "presa_forza",
"pmid": "41095962",
"doi": "10.3390/jcm14196882",
"titolo": "Hand-Focused Strength and Proprioceptive Training for Improving Grip Strength and Manual Dexterity in Healthy Adults: A Systematic Review and Meta-Analysis",
"rivista": "Journal of clinical medicine",
"anno": "2025",
"autore": "Akbaş A.",
"oa": true,
"cit": 5,
"tema": "selezione",
"liv": "B",
"sintesi": "Allenamento specifico di mano e propriocezione per migliorare la forza di presa: la presa si allena, e non migliora da sola con i tiri.",
"kw": "presa avambraccio forza"
},
{
"id": "panca_presa",
"pmid": "39178098",
"doi": "10.1519/jsc.0000000000004920",
"titolo": "Influence of Grip Width on the Load-Velocity Relationship and 1 Repetition Maximum Value in the Bench Press Exercise: A Comparative and Reliability Analysis of Mean Velocity Vs. Mean Propulsive Velocity Vs. Peak Velocity",
"rivista": "Journal of strength and conditioning research",
"anno": "2024",
"autore": "Herrera-Bermudo JC",
"oa": false,
"cit": 1,
"tema": "selezione",
"liv": "B",
"sintesi": "La larghezza della presa in panca cambia la relazione fra carico e velocità e il massimale espresso. Non è un dettaglio neutro.",
"kw": "presa larghezza panca velocità"
},
{
"id": "squat_regional",
"pmid": "36498298",
"doi": "10.3390/ijerph192316226",
"titolo": "Does Back Squat Exercise Lead to Regional Hypertrophy among Quadriceps Femoris Muscles?",
"rivista": "International journal of environmental research and public health",
"anno": "2022",
"autore": "Kojic F",
"oa": true,
"cit": 2,
"tema": "selezione",
"liv": "B",
"sintesi": "Lo squat produce ipertrofia regionale disomogenea nel quadricipite: cresce soprattutto il vasto laterale, molto meno il retto femorale.",
"kw": "squat quadricipite retto femorale regionale"
},
{
"id": "pec_fiber",
"pmid": "35093733",
"doi": "10.1016/j.jbiomech.2022.110966",
"titolo": "Differential regional pectoralis major activation indicates functional diversity in healthy females",
"rivista": "Journal of biomechanics",
"anno": "2022",
"autore": "Lulic-Kuryllo T",
"oa": false,
"cit": 5,
"tema": "selezione",
"liv": "B",
"sintesi": "Il grande pettorale si attiva per regioni distinte a seconda della direzione del movimento: clavicolare e sternale non sono intercambiabili.",
"kw": "pettorale regioni clavicolare sternale"
},
{
"id": "glute_exercises",
"pmid": "30140560",
"doi": "10.26603/ijspt20180668",
"titolo": "Electromyographic Analysis of Gluteus Maximus, Gluteus Medius, and Tensor Fascia Latae During Therapeutic Exercises With and Without Elastic Resistance",
"rivista": "International journal of sports physical therapy",
"anno": "2018",
"autore": "Bishop BN",
"oa": false,
"cit": 15,
"tema": "selezione",
"liv": "B",
"sintesi": "Analisi elettromiografica di grande gluteo, medio gluteo e tensore della fascia lata nei principali esercizi.",
"kw": "glutei elettromiografia esercizi"
},
{
"id": "pressa_squat",
"pmid": "27735888",
"doi": "10.23736/s0022-4707.16.06698-6",
"titolo": "Strength, body composition, and functional outcomes in the squat versus leg press exercises",
"rivista": "The Journal of sports medicine and physical fitness",
"anno": "2018",
"autore": "Rossi FE",
"oa": false,
"cit": 28,
"tema": "selezione",
"liv": "B",
"sintesi": "Squat contro leg press su forza, composizione corporea ed esiti funzionali: risultati vicini, con trasferimenti specifici diversi.",
"kw": "pressa squat confronto"
},
{
"id": "bourne_hamstring",
"pmid": "27467123",
"doi": "10.1136/bjsports-2015-095739",
"titolo": "Impact of exercise selection on hamstring muscle activation",
"rivista": "British journal of sports medicine",
"anno": "2017",
"autore": "Bourne MN",
"oa": false,
"cit": 145,
"tema": "selezione",
"liv": "B",
"sintesi": "Confronto in risonanza dell’attivazione dei singoli capi degli ischiocrurali fra esercizi: la selezione dell’esercizio cambia quale capo lavora.",
"kw": "femorali capi esercizi selezione"
},
{
"id": "schoenfeld_range_att",
"pmid": "24978835",
"doi": "10.1519/jsc.0000000000000598",
"titolo": "Regional differences in muscle activation during hamstrings exercise",
"rivista": "Journal of strength and conditioning research",
"anno": "2015",
"autore": "Schoenfeld BJ",
"oa": false,
"cit": 39,
"tema": "selezione",
"liv": "B",
"sintesi": "Differenze regionali di attivazione degli ischiocrurali fra esercizi: la selezione decide quale porzione del muscolo lavora.",
"kw": "femorali attivazione regionale esercizi"
},
{
"id": "pulldown_presa",
"pmid": "24662157",
"doi": "10.1097/jsc.0000000000000232",
"titolo": "Effects of grip width on muscle strength and activation in the lat pull-down",
"rivista": "Journal of strength and conditioning research",
"anno": "2014",
"autore": "Andersen V",
"oa": false,
"cit": 18,
"tema": "selezione",
"liv": "B",
"sintesi": "La larghezza della presa alla lat machine cambia forza espressa e attivazione: le differenze fra prese sono minori di quanto si crede.",
"kw": "lat machine presa larghezza"
},
{
"id": "loenneke_bfr",
"pmid": "42549104",
"doi": "10.3389/fphys.2026.1812707",
"titolo": "Muscle hypertrophy and strength improvements following blood flow restriction combined with resistance training in team-athletes: a systematic review and meta-analysis",
"rivista": "Frontiers in physiology",
"anno": "2026",
"autore": "Huang Q",
"oa": true,
"cit": 0,
"tema": "tecniche",
"liv": "A",
"sintesi": "Meta-analisi recente su ipertrofia e forza con restrizione del flusso: conferma il quadro, con indicazioni su pressione e protocollo.",
"kw": "BFR restrizione protocollo"
},
{
"id": "schoenfeld_eccentric",
"pmid": "39652733",
"doi": "10.1519/jsc.0000000000004981",
"titolo": "Comparison Between Eccentric vs. Concentric Muscle Actions On Hypertrophy: A Systematic Review and Meta-analysis",
"rivista": "Journal of strength and conditioning research",
"anno": "2025",
"autore": "da Silva LSL",
"oa": false,
"cit": 3,
"tema": "tecniche",
"liv": "A",
"sintesi": "Confronto fra azione eccentrica e concentrica sull’ipertrofia: le differenze sono piccole, con una leggera tendenza a favore dell’eccentrica.",
"kw": "eccentrico concentrico azione"
},
{
"id": "grgic_dropset",
"pmid": "37523092",
"doi": "10.1186/s40798-023-00620-5",
"titolo": "Effects of Drop Sets on Skeletal Muscle Hypertrophy: A Systematic Review and Meta-analysis",
"rivista": "Sports medicine - open",
"anno": "2023",
"autore": "Sødal LK",
"oa": true,
"cit": 10,
"tema": "tecniche",
"liv": "A",
"sintesi": "Rassegna sistematica sui drop set: producono ipertrofia paragonabile alle serie tradizionali a volume più basso e in meno tempo. Utili come strumento di efficienza, non come stimolo superiore.",
"kw": "drop set stripping efficienza"
},
{
"id": "sodergren_restpause",
"pmid": "34260860",
"doi": "10.1139/apnm-2021-0278",
"titolo": "Rest-pause and drop-set training elicit similar strength and hypertrophy adaptations compared with traditional sets in resistance-trained males",
"rivista": "Applied physiology, nutrition, and metabolism = Physiologie appliquee, nutrition et metabolisme",
"anno": "2021",
"autore": "Enes A",
"oa": false,
"cit": 15,
"tema": "tecniche",
"liv": "B",
"sintesi": "Rest-pause e drop set danno forza e ipertrofia simili alle serie tradizionali. Servono a risparmiare tempo, non ad aggiungere stimolo.",
"kw": "rest pause serie tradizionali"
},
{
"id": "weakley_superset",
"pmid": "28796130",
"doi": "10.1519/jsc.0000000000002179",
"titolo": "The Effects of Superset Configuration on Kinetic, Kinematic, and Perceived Exertion in the Barbell Bench Press",
"rivista": "Journal of strength and conditioning research",
"anno": "2020",
"autore": "Weakley JJS",
"oa": false,
"cit": 19,
"tema": "tecniche",
"liv": "B",
"sintesi": "Le superserie riducono il tempo di seduta ma peggiorano velocità e potenza espresse, e alzano lo sforzo percepito. Compromesso, non pasto gratis.",
"kw": "superserie tempo sforzo"
},
{
"id": "lixandrao_bfr",
"pmid": "29043659",
"doi": "10.1007/s40279-017-0795-y",
"titolo": "Magnitude of Muscle Strength and Mass Adaptations Between High-Load Resistance Training Versus Low-Load Resistance Training Associated with Blood-Flow Restriction: A Systematic Review and Meta-Analysis",
"rivista": "Sports medicine (Auckland, N.Z.)",
"anno": "2018",
"autore": "Lixandrão ME",
"oa": false,
"cit": 348,
"tema": "tecniche",
"liv": "A",
"sintesi": "Meta-analisi su restrizione del flusso sanguigno con carichi bassi contro carichi alti: l’ipertrofia è paragonabile, la forza massimale resta a favore dei carichi alti.",
"kw": "restrizione flusso BFR carichi bassi"
},
{
"id": "speirs_unilateral",
"pmid": "26200193",
"doi": "10.1519/jsc.0000000000001096",
"titolo": "Unilateral vs. Bilateral Squat Training for Strength, Sprints, and Agility in Academy Rugby Players",
"rivista": "Journal of strength and conditioning research",
"anno": "2016",
"autore": "Speirs DE",
"oa": false,
"cit": 70,
"tema": "tecniche",
"liv": "B",
"sintesi": "Squat unilaterale contro bilaterale su forza, sprint e agilità: entrambi funzionano, con trasferimenti specifici diversi.",
"kw": "unilaterale bilaterale monopodalico"
},
{
"id": "schoenfeld_tempo",
"pmid": "25601394",
"doi": "10.1007/s40279-015-0304-0",
"titolo": "Effect of repetition duration during resistance training on muscle hypertrophy: a systematic review and meta-analysis",
"rivista": "Sports medicine (Auckland, N.Z.)",
"anno": "2015",
"autore": "Schoenfeld BJ",
"oa": false,
"cit": 83,
"tema": "tecniche",
"liv": "A",
"sintesi": "Meta-analisi sulla durata della ripetizione: nell’intervallo da mezzo secondo a otto secondi per fase non emergono differenze di ipertrofia. Contare i tempi non serve.",
"kw": "tempo cadenza durata ripetizione"
},
{
"id": "roig_eccentric",
"pmid": "18981046",
"doi": "10.1136/bjsm.2008.051417",
"titolo": "The effects of eccentric versus concentric resistance training on muscle strength and mass in healthy adults: a systematic review with meta-analysis",
"rivista": "British journal of sports medicine",
"anno": "2009",
"autore": "Roig M",
"oa": false,
"cit": 399,
"tema": "tecniche",
"liv": "A",
"sintesi": "Meta-analisi storica su eccentrico contro concentrico: l’eccentrico produce più forza e massa quando l’intensità è più alta, che è quasi sempre il caso.",
"kw": "eccentrico forza massa"
},
{
"id": "pelland_volume",
"pmid": "41343037",
"doi": "10.1007/s40279-025-02344-w",
"titolo": "The Resistance Training Dose Response: Meta-Regressions Exploring the Effects of Weekly Volume and Frequency on Muscle Hypertrophy and Strength Gains",
"rivista": "Sports medicine (Auckland, N.Z.)",
"anno": "2026",
"autore": "Pelland JC",
"oa": false,
"cit": 4,
"tema": "volume",
"liv": "A",
"sintesi": "67 studi, 2058 soggetti. L’ipertrofia cresce con il volume settimanale senza un tetto netto, ma con rendimenti decrescenti: circa +0,24% di ipertrofia per serie aggiunta intorno alle 12 serie settimanali. La frequenza, a volume pari, non ha un effetto identificabile sull’ipertrofia.",
"kw": "volume serie settimanali dose risposta frequenza"
},
{
"id": "currier_volume",
"pmid": "37414459",
"doi": "10.1136/bjsports-2023-106807",
"titolo": "Resistance training prescription for muscle strength and hypertrophy in healthy adults: a systematic review and Bayesian network meta-analysis",
"rivista": "British journal of sports medicine",
"anno": "2023",
"autore": "Currier BS",
"oa": true,
"cit": 125,
"tema": "volume",
"liv": "A",
"sintesi": "Meta-analisi bayesiana a rete sulla prescrizione: volume, carico e frequenza confrontati su forza e ipertrofia in adulti sani.",
"kw": "prescrizione volume carico frequenza"
},
{
"id": "volume_alto",
"pmid": "30153194",
"doi": "10.1249/mss.0000000000001764",
"titolo": "Resistance Training Volume Enhances Muscle Hypertrophy but Not Strength in Trained Men",
"rivista": "Medicine and science in sports and exercise",
"anno": "2019",
"autore": "Schoenfeld BJ",
"oa": true,
"cit": 181,
"tema": "volume",
"liv": "B",
"sintesi": "Su uomini allenati, alzare il volume aumenta l’ipertrofia ma non la forza. Conferma che le due qualità hanno curve dose-risposta diverse.",
"kw": "volume alto allenati forza ipertrofia"
},
{
"id": "ralston_volume",
"pmid": "28755103",
"doi": "10.1007/s40279-017-0762-7",
"titolo": "The Effect of Weekly Set Volume on Strength Gain: A Meta-Analysis",
"rivista": "Sports medicine (Auckland, N.Z.)",
"anno": "2017",
"autore": "Ralston GW",
"oa": true,
"cit": 147,
"tema": "volume",
"liv": "A",
"sintesi": "Meta-analisi sul volume settimanale e i guadagni di forza: più serie danno più forza, con rendimenti decrescenti.",
"kw": "volume forza serie"
},
{
"id": "krieger_sets",
"pmid": "20300012",
"doi": "10.1519/jsc.0b013e3181d4d436",
"titolo": "Single vs. multiple sets of resistance exercise for muscle hypertrophy: a meta-analysis",
"rivista": "Journal of strength and conditioning research",
"anno": "2010",
"autore": "Krieger JW.",
"oa": false,
"cit": 156,
"tema": "volume",
"liv": "A",
"sintesi": "Serie multiple producono più ipertrofia della serie singola, con un effetto dose-risposta chiaro. È il lavoro che ha chiuso la questione del monoserie.",
"kw": "serie multiple singola volume"
}
];
